module.exports = {
  keywordFeedback: {
    team: {
      positive: [
        "Your emphasis on teamwork aligns well with our collaborative culture.",
        "We appreciate candidates who value working in a team environment.",
        "Your collaborative spirit is a strong asset.",
        "It's great to hear how you contribute to team success.",
        "Your ability to work well with others is commendable.",
        "You demonstrate a strong understanding of team dynamics.",
        "Your examples of teamwork are impressive and relevant.",
        "We value your approach to fostering a positive team environment.",
      ],
      negative: [
        "Consider highlighting how you contribute to a team setting.",
        "Teamwork is essential here; think about ways to showcase your collaborative skills.",
        "We'd like to hear more about your experiences working with others.",
        "Sharing examples of teamwork could strengthen your response.",
        "Think about discussing specific team projects you've been a part of.",
        "Providing more details on your role within a team could be beneficial.",
        "Consider explaining how you handle conflicts within a team.",
        "We'd appreciate hearing about your strategies for effective teamwork.",
      ],
    },
    leadership: {
      positive: [
        "Your leadership experiences are impressive and crucial for growth.",
        "We value strong leaders who can inspire and guide others.",
        "Your ability to lead and motivate others stands out.",
        "Demonstrating leadership is a key quality we admire.",
        "Your examples of leadership are both relevant and impactful.",
        "You show a clear understanding of effective leadership principles.",
        "Your leadership style seems well-suited to our organizational culture.",
        "We appreciate your ability to take charge and drive results.",
      ],
      negative: [
        "It might help to provide specific examples of your leadership skills.",
        "Think about situations where you've taken the lead to achieve goals.",
        "Highlighting leadership experiences could enhance your answer.",
        "We encourage you to share how you've guided others in the past.",
        "Consider discussing your approach to leadership challenges.",
        "Providing more context on your leadership roles could be beneficial.",
        "We'd like to hear about your strategies for motivating a team.",
        "Think about sharing how you handle leadership responsibilities.",
      ],
    },
    communication: {
      positive: [
        "Your communication skills are clear and effective.",
        "We appreciate how well you articulate your thoughts.",
        "Strong communication is vital, and you demonstrate it well.",
        "Your ability to convey ideas is commendable.",
        "You have a knack for explaining complex concepts simply.",
        "Your communication style is both engaging and informative.",
        "We value your ability to listen and respond thoughtfully.",
        "Your examples of effective communication are impressive.",
      ],
      negative: [
        "Consider working on expressing your ideas more clearly.",
        "Improving your communication can enhance your effectiveness.",
        "We'd like to hear more detailed explanations from you.",
        "Clarifying your points could strengthen your response.",
        "Think about providing more structured and concise answers.",
        "We'd appreciate more examples of your communication skills.",
        "Consider discussing how you handle difficult conversations.",
        "Providing more context on your communication experiences could be helpful.",
      ],
    },
    problemSolving: {
      positive: [
        "Your problem-solving abilities are impressive.",
        "We value your analytical approach to tackling challenges.",
        "Your solutions-oriented mindset is a great asset.",
        "Demonstrating critical thinking is highly appreciated.",
        "Your examples of problem-solving are both relevant and insightful.",
        "You show a strong ability to identify and address issues.",
        "We appreciate your methodical approach to problem-solving.",
        "Your ability to think on your feet is commendable.",
      ],
      negative: [
        "Consider providing examples of how you solve problems.",
        "We'd like to hear more about your approach to overcoming obstacles.",
        "Sharing your problem-solving process could enhance your answer.",
        "Think about discussing how you handle complex situations.",
        "Providing more details on your problem-solving strategies could be beneficial.",
        "We'd appreciate hearing about specific challenges you've faced.",
        "Consider explaining how you evaluate and implement solutions.",
        "Think about sharing how you collaborate with others to solve problems.",
      ],
    },
    adaptability: {
      positive: [
        "Your flexibility in adapting to new situations is commendable.",
        "We appreciate your willingness to embrace change.",
        "Adaptability is crucial, and you exhibit it well.",
        "Your ability to adjust to new challenges is impressive.",
        "You demonstrate a strong capacity for handling change.",
        "Your examples of adaptability are both relevant and impactful.",
        "We value your proactive approach to adapting to new environments.",
        "Your ability to remain calm under pressure is commendable.",
      ],
      negative: [
        "Consider sharing how you handle unexpected changes.",
        "Adaptability is key; think about ways to demonstrate your flexibility.",
        "We'd like to know more about how you adapt to new environments.",
        "Providing examples of adaptability could strengthen your response.",
        "Think about discussing specific instances where you've had to adapt.",
        "We'd appreciate more details on your approach to change management.",
        "Consider explaining how you stay productive during transitions.",
        "Think about sharing how you support others during periods of change.",
      ],
    },
    creativity: {
      positive: [
        "Your creative thinking brings valuable perspectives.",
        "We appreciate your innovative ideas and approaches.",
        "Creativity is a strong asset, and you display it effectively.",
        "Your ability to think outside the box is impressive.",
        "You demonstrate a strong capacity for generating new ideas.",
        "Your examples of creativity are both relevant and impactful.",
        "We value your ability to find unique solutions to problems.",
        "Your innovative mindset is a great asset to our team.",
      ],
      negative: [
        "Consider showcasing how you bring creativity to your work.",
        "We'd like to hear more about your innovative solutions.",
        "Sharing creative examples could enhance your answer.",
        "Think about discussing how you approach problems creatively.",
        "Providing more details on your creative process could be beneficial.",
        "We'd appreciate hearing about specific creative projects you've worked on.",
        "Consider explaining how you foster creativity in a team setting.",
        "Think about sharing how you stay inspired and generate new ideas.",
      ],
    },
    timeManagement: {
      positive: [
        "Your ability to manage time effectively is impressive.",
        "We value your organizational skills and punctuality.",
        "Effective time management is crucial, and you demonstrate it well.",
        "Your prioritization skills are commendable.",
        "You show a strong capacity for balancing multiple tasks.",
        "Your examples of time management are both relevant and impactful.",
        "We appreciate your ability to meet deadlines consistently.",
        "Your organizational skills are a great asset to our team.",
      ],
      negative: [
        "Consider discussing how you prioritize tasks.",
        "Improving time management can enhance your productivity.",
        "We'd like to hear more about how you handle deadlines.",
        "Sharing strategies for managing your time could strengthen your response.",
        "Think about providing more details on your time management techniques.",
        "We'd appreciate hearing about specific challenges you've faced with time management.",
        "Consider explaining how you stay organized and focused.",
        "Think about sharing how you balance competing priorities.",
      ],
    },
    initiative: {
      positive: [
        "Your proactive approach is highly appreciated.",
        "We value candidates who take initiative, and you exemplify that.",
        "Demonstrating initiative shows your commitment to success.",
        "Your willingness to go above and beyond is commendable.",
        "You show a strong capacity for identifying and addressing needs.",
        "Your examples of initiative are both relevant and impactful.",
        "We appreciate your ability to take charge and drive results.",
        "Your proactive mindset is a great asset to our team.",
      ],
      negative: [
        "Consider sharing instances where you took initiative.",
        "We'd like to hear more about how you proactively address challenges.",
        "Highlighting your initiative can strengthen your response.",
        "Think about discussing times when you went beyond your responsibilities.",
        "Providing more details on your proactive efforts could be beneficial.",
        "We'd appreciate hearing about specific challenges you've faced and addressed.",
        "Consider explaining how you identify opportunities for improvement.",
        "Think about sharing how you motivate others to take initiative.",
      ],
    },
    technicalSkills: {
      positive: [
        "Your technical expertise is impressive and relevant.",
        "We appreciate your strong foundation in key technical areas.",
        "Demonstrating solid technical skills adds great value.",
        "Your proficiency with these technologies is commendable.",
        "You show a strong capacity for applying technical knowledge.",
        "Your examples of technical skills are both relevant and impactful.",
        "We value your ability to stay current with industry trends.",
        "Your technical acumen is a great asset to our team.",
      ],
      negative: [
        "Consider elaborating on your technical skills and experiences.",
        "We'd like to know more about your proficiency in relevant technologies.",
        "Highlighting specific technical accomplishments could enhance your answer.",
        "Think about discussing how your technical skills apply to this role.",
        "Providing more details on your technical projects could be beneficial.",
        "We'd appreciate hearing about specific challenges you've faced and overcome.",
        "Consider explaining how you stay updated with new technologies.",
        "Think about sharing how you apply technical skills to solve problems.",
      ],
    },
    customerFocus: {
      positive: [
        "Your dedication to customer satisfaction stands out.",
        "We value a strong customer focus, and you demonstrate that well.",
        "Your understanding of customer needs is impressive.",
        "Demonstrating empathy towards customers is highly appreciated.",
        "You show a strong capacity for building customer relationships.",
        "Your examples of customer focus are both relevant and impactful.",
        "We appreciate your ability to address customer concerns effectively.",
        "Your customer-centric mindset is a great asset to our team.",
      ],
      negative: [
        "Consider sharing how you ensure customer satisfaction.",
        "We'd like to hear more about your experiences with customer interactions.",
        "Highlighting your customer service skills could strengthen your response.",
        "Think about discussing how you handle customer feedback.",
        "Providing more details on your approach to customer service could be beneficial.",
        "We'd appreciate hearing about specific challenges you've faced with customers.",
        "Consider explaining how you build and maintain customer relationships.",
        "Think about sharing how you address and resolve customer issues.",
      ],
    },
    innovation: {
      positive: [
        "Your innovative ideas can drive significant improvements.",
        "We appreciate your forward-thinking approach.",
        "Demonstrating innovation is key to our growth.",
        "Your ability to introduce new concepts is commendable.",
        "You show a strong capacity for generating innovative solutions.",
        "Your examples of innovation are both relevant and impactful.",
        "We value your ability to think ahead and anticipate needs.",
        "Your innovative mindset is a great asset to our team.",
      ],
      negative: [
        "Consider discussing how you've contributed innovative ideas.",
        "We'd like to hear more about your approach to innovation.",
        "Sharing examples of innovation could enhance your answer.",
        "Think about how you stay ahead with new trends and technologies.",
        "Providing more details on your innovative projects could be beneficial.",
        "We'd appreciate hearing about specific challenges you've faced and addressed innovatively.",
        "Consider explaining how you foster a culture of innovation.",
        "Think about sharing how you encourage others to think creatively.",
      ],
    },
  },
  sentimentFeedback: {
    positive: [
      "That's great to hear! Your response shows enthusiasm and positivity.",
      "Your positive outlook is refreshing and much appreciated.",
      "Your enthusiasm is contagious; we're glad to see your passion.",
      "We appreciate your upbeat attitude and energy.",
      "Your positive attitude is a great asset to our team.",
      "You demonstrate a strong capacity for maintaining a positive outlook.",
      "Your examples of positivity are both relevant and impactful.",
      "We value your ability to stay optimistic and motivated.",
    ],
    neutral: [
      "Thank you for sharing that. Could you elaborate more?",
      "We appreciate your response. Providing more details might help us understand better.",
      "Your answer is informative; additional examples could enhance it.",
      "Consider expanding on your points for greater clarity.",
      "We'd like to hear more about your experiences and perspectives.",
      "Providing more context could help us better understand your response.",
      "Consider explaining your thoughts in more detail.",
      "Think about sharing specific examples to illustrate your points.",
    ],
    negative: [
      "Thank you for your honesty. It might be helpful to focus on positive aspects or learning experiences.",
      "We appreciate your candidness. Consider highlighting what you've learned from these experiences.",
      "Reflecting on the positive outcomes can strengthen your response.",
      "Think about how challenges have helped you grow and develop.",
      "Providing more details on how you've overcome difficulties could be beneficial.",
      "We'd appreciate hearing about the lessons you've learned from negative experiences.",
      "Consider explaining how you've turned challenges into opportunities.",
      "Think about sharing how you've grown from difficult situations.",
    ],
    mixed: [
      "We notice both positive and challenging aspects in your response.",
      "Your answer shows complexity; focusing on key points might help.",
      "Consider balancing your response with both strengths and areas for growth.",
      "Providing a clearer stance could enhance your answer.",
      "We'd like to hear more about how you navigate both positive and negative experiences.",
      "Providing more context on your mixed experiences could be beneficial.",
      "Consider explaining how you balance different aspects of your experiences.",
      "Think about sharing how you integrate both positive and negative feedback.",
    ],
    unclear: [
      "We had some difficulty understanding your response; could you clarify?",
      "Clarifying your points might help us better grasp your perspective.",
      "Consider rephrasing for clearer communication.",
      "We'd appreciate more detail to fully understand your answer.",
      "Providing more context could help us better understand your response.",
      "Consider explaining your thoughts in more detail.",
      "Think about sharing specific examples to illustrate your points.",
      "We'd like to hear more about your experiences and perspectives.",
    ],
  },
};
